### PR TITLE
Update to JDA v5 and reaction roles.

### PR DESCRIPTION
**Pull request by Matyrobbrt**
The update to JDA v5 also gives access to threads and timeouts, so the bot could be made to create threads in the commissions and suggestions channels.

### CODE REVIEW

**Comment by KiriCattus** [comment]
Fixes to gradle scripts I accidentilly broke have been pushed so things can build without failing, could I ask what this new roles panel thing is though as I've not looked at JDA5 just yet because I was unsure of it's stability and also haven't had time just yet 😅

**Comment by Matyrobbrt** [comment]
Both chewtils and jda v5 are very stable I've been using them for a month. And I remember jas saying that she wants something for the role which would give people the ability to talk without a phone number. Let me see if I can find the message

Edit: https://discord.com/channels/176780432371744769/176780432371744769/934059279680409610

**Comment by KiriCattus** [comment]
Ah that's what the role panels is? I understood the other one was a command to make the bot react to a message though, and yes I know of the feature you mean it's a high priority I've just not had time to figure out :s

**Comment by Matyrobbrt** [comment]
Yea, role panels are a fancier way of saying reaction roles :P

**Comment by KiriCattus** [comment]
I think we have a similar concept system in place for the request channels but it's hidden deep in the other stuff [here](https://github.com/MinecraftModDevelopment/MMDBot/blob/3.0/src/main/java/com/mcmoddev/mmdbot/modules/logging/misc/EventReactionAdded.java) Not the exact same though xD

**Comment by Matyrobbrt** [comment]
The latest commit updates to JDA5 alpha 5, which is the interactions rework.. Since I am at it, I will add some context menus

**Comment by Matyrobbrt** [comment]
I was also thinking about actually implementing an warning system, but I don't know if that is needed.


Edit: after a discussion on discord, I will add that

**Review by KiriCattus — APPROVED** [review]

**Comment by Matyrobbrt** [comment]
Ok so this PR is now way out of it's initial scope, so here is what it adds:
- Update to JDA5 alpha 5
- Reaction Roles
- Automatic thread creation for suggestions / free mod ideas channel
- _Finally_ fixes the `/user` command to display the server join time
- Context menus for:
   - Creating gists
   - `/me` command
   - Quoting an entire message
- Warnings system
- Splits command and button interaction handling in multiple threads, in order to:
   - speed things up
   - avoid runtime exceptions blocking the entire event thread

**Review by KiriCattus — APPROVED** [review]

**Pull request merged**
