### PR TITLE
Implement search command class to replace the specialised classes

### PR DESCRIPTION
**Pull request by williambl**
Also adds url encoding.

### CODE REVIEW

**Review by KiriCattus — CHANGES_REQUESTED** [review]
Everything looks great just please don't use single package imports (``info.server.*``) I thought I'd setup the style script to take care of that though so likely my fault.

**Comment by williambl** [comment]
Fixed.

**Comment by williambl** [comment]
wait i forgot to push

**Comment by williambl** [comment]
See #34

**Pull request merged**
